In [4]:
import torchreid
from torchreid.utils import FeatureExtractor
import numpy as np
import torch.nn.functional as F
import torch

In [5]:
torchreid.models.show_avai_models()

['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0', 'osnet_ain_x0_75', 'osnet_ain_x0_5', 'osnet_ain_x0_25']


In [3]:
extractor = FeatureExtractor(
    model_name='osnet_ain_x1_0',
    device='cuda'
)

Successfully loaded imagenet pretrained weights from "/home/mohamed-emad/.cache/torch/checkpoints/osnet_ain_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Model: osnet_ain_x1_0
- params: 2,193,616
- flops: 978,878,352


In [48]:
img_list = [
    "/home/mohamed-emad/Pictures/ME,MYSELF&I/google-profile.jpg",
    "/home/mohamed-emad/Pictures/ME,MYSELF&I/IMG-20251113-WA0029.jpg",
    "/home/mohamed-emad/Pictures/ME,MYSELF&I/IMG_20240920_162321.jpg",
    "/home/mohamed-emad/Pictures/ME,MYSELF&I/IMG_20260411_135344.jpg",
    "/home/mohamed-emad/Pictures/ME,MYSELF&I/IMG_20260411_135604.jpg",
    "/home/mohamed-emad/Pictures/andrew1.jpeg",
    "/home/mohamed-emad/Pictures/andrew2.jpeg",
    "/home/mohamed-emad/Pictures/andrew3.jpeg",
    "/home/mohamed-emad/Pictures/andrew4.jpeg",
]

In [49]:
fs = extractor(img_list)

In [50]:
torch.reshape(fs[0], (1,-1)).shape

torch.Size([1, 512])

In [51]:
torch.tensor((len(img_list), len(img_list)))

tensor([9, 9])

In [52]:
r = torch.zeros((len(img_list), len(img_list)))
r[0 ,1] = 1
r

tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [53]:
r = torch.zeros((len(img_list), len(img_list)))
for i in range(0, len(img_list)):
    for j in range(0, len(img_list)):
        r[i][j] = F.cosine_similarity(torch.reshape(fs[i], (1,-1)), torch.reshape(fs[j], (1,-1)), dim=1)
r

tensor([[1.0000, 0.5221, 0.5447, 0.7259, 0.6267, 0.4611, 0.4989, 0.5027, 0.5176],
        [0.5221, 1.0000, 0.4469, 0.5923, 0.6071, 0.3982, 0.5011, 0.6312, 0.5421],
        [0.5447, 0.4469, 1.0000, 0.4870, 0.5180, 0.4359, 0.4767, 0.3679, 0.4520],
        [0.7259, 0.5923, 0.4870, 1.0000, 0.6780, 0.4423, 0.5722, 0.6004, 0.5922],
        [0.6267, 0.6071, 0.5180, 0.6780, 1.0000, 0.5086, 0.5910, 0.5919, 0.6528],
        [0.4611, 0.3982, 0.4359, 0.4423, 0.5086, 1.0000, 0.5501, 0.4120, 0.4733],
        [0.4989, 0.5011, 0.4767, 0.5722, 0.5910, 0.5501, 1.0000, 0.6258, 0.7197],
        [0.5027, 0.6312, 0.3679, 0.6004, 0.5919, 0.4120, 0.6258, 1.0000, 0.6353],
        [0.5176, 0.5421, 0.4520, 0.5922, 0.6528, 0.4733, 0.7197, 0.6353, 1.0000]])